- hosts: nginxservers
  become: true
  tasks:
  - name: ansible create directory example
    file:
      path: /home/ubuntu/atiyeh
      state: directory
 
  - name: Creating a file with content
    copy:
      dest: "/home/ubuntu/atiyeh/word.txt"
      content:
        hahaha

        hehe

        helo

        helo

