- hosts: nginxservers
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes   

    - name: Install python3 package
      apt:
        name: python3
        state: present
        update_cache: True
    - name: Install python3 package
      apt:
        name: python3-pip
        state: present
        update_cache: True

    - name: install boto3 and botocore python3 packages
      pip:
        name:
          - boto3
          - botocore
        executable: pip3
     

    - name: "Simple PUT operation"
      aws_s3:
        bucket: "{{ bucketname }}"
        object: word.txt
        src: /home/ubuntu/atiyeh/word.txt
        mode: put
        aws_access_key: 5aa7ee1f-12e0-4b8c-94e9-899565878812
        aws_secret_key: 6f843872771119af8def91d47a561725d9d37bdd971d9c1f10af5cd0bcfd9011
        encrypt: false
        s3_url: https://s3.ir-thr-at1.arvanstorage.com
      vars:
        bucketname: atiyeh