- hosts: nginxservers
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes   

    - name: Install python3 package
      apt:
        name: python3
        state: present
        update_cache: True
    - name: Install python3 package
      apt:
        name: python3-pip
        state: present
        update_cache: True

    - name: install boto3 and botocore python3 packages
      pip:
        name:
          - boto3
          - botocore
        executable: pip3
     

    - name: "Simple PUT operation"
      aws_s3:
        bucket: "{{ bucketname }}"
        object: word.txt
        src: /home/ubuntu/atiyeh/word.txt
        mode: put
        aws_access_key: *
        aws_secret_key: *****
        encrypt: false
        s3_url: https://s3.
      vars:
        bucketname: atiyeh